version: "3"
services:
  node:
    container_name: web
    build: ./
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
    command:
      sh -c 'npm i && node index.js'
    links:
      - redis
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    expose:
      - 6379